from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, field_validator
from pydantic.json_schema import SkipJsonSchema

# Fields annotated with ``SkipJsonSchema`` are assigned by the harness after
# the model call (tiering, URL health, failure status). They stay out of the
# model-facing output schema so the model is never asked to guess them.


class VeracityVerdict(str, Enum):
    SUPPORTED = "Supported"
    REFUTED = "Refuted"
    NOT_ENOUGH_EVIDENCE = "Not Enough Evidence"
    CONFLICTING = "Conflicting Evidence/Cherrypicking"


class EvidenceSignal(str, Enum):
    SUPPORTS = "supports"
    REFUTES = "refutes"
    MIXED = "mixed"
    INSUFFICIENT = "insufficient"


class ReviewAction(str, Enum):
    FINALIZE = "finalize"
    FOLLOW_UP = "follow_up"


class FindingStatus(str, Enum):
    """Whether a check produced an observation or the harness failed to run it.

    A ``failed`` or ``budget_exhausted`` check is a missing observation, not
    evidence of absence; downstream stages must not read it as ``insufficient``
    evidence about the world.
    """

    COMPLETED = "completed"
    FAILED = "failed"
    BUDGET_EXHAUSTED = "budget_exhausted"


class SourceTier(str, Enum):
    """Deterministic authority tier assigned from the source domain."""

    PRIMARY = "primary"  # official, governmental, institutional, scientific, legal
    REFERENCE = "reference"  # encyclopedias, archives, curated datasets
    NEWS = "news"  # established news organizations and wire services
    FACT_CHECKER = "fact_checker"  # dedicated fact-checking organizations
    USER_GENERATED = "user_generated"  # social media, forums, blogging platforms
    OTHER = "other"


class UrlStatus(str, Enum):
    """Result of the optional post-judge citation health check."""

    LIVE = "live"
    ARCHIVED = "archived"
    BROKEN = "broken"


class CheckworthyClaim(BaseModel):
    claim_id: str = Field(description="Stable identifier for the extracted claim.")
    claim_text: str = Field(
        description=(
            "Standalone, decontextualized, atomic factual claim suitable for independent checking."
        )
    )
    source_fragment: str = Field(
        description="Short fragment from the input text that directly grounds this claim."
    )
    checkworthy_reason: str = Field(
        description="Why this claim is check-worthy (impact, specificity, verifiability)."
    )


class ClaimExtractionResult(BaseModel):
    """Structured output from claim extraction with coverage metadata."""
    input_text: str = Field(description="Original input text that was processed.")
    detected_language: str = Field(
        default="",
        description=(
            "ISO 639-1 code of the input's dominant language (e.g. 'cs', 'sk', 'pl', 'en'). "
            "All generated claim text is written in this language."
        ),
    )
    claims: list[CheckworthyClaim] = Field(default_factory=list)
    coverage_notes: list[str] = Field(
        default_factory=list,
        description="How extraction covers the factual content from the input.",
    )
    excluded_nonfactual: list[str] = Field(
        default_factory=list,
        description="Statements intentionally excluded as non-factual/opinion/rhetoric.",
    )


class SourceEvidence(BaseModel):
    """Source snippet attached to findings and final verdict justification."""
    title: str = Field(description="Human-readable title of the source.")
    url: str = Field(description="URL used during fact-checking.")
    snippet: str = Field(description="Short text span from the source backing the claim.")
    publisher: str | None = Field(default=None)
    published_at: str | None = Field(default=None)
    tier: SkipJsonSchema[SourceTier | None] = None
    url_status: SkipJsonSchema[UrlStatus | None] = None
    archived_url: SkipJsonSchema[str | None] = None

    @field_validator("url")
    @classmethod
    def url_must_be_http(cls, value: str) -> str:
        stripped = value.strip()
        if stripped and not stripped.startswith(("http://", "https://")):
            raise ValueError(f"url must start with http:// or https://, got: {stripped!r}")
        return stripped


class VerificationCheck(BaseModel):
    """Single independent verification question generated by planning."""
    aspect_id: str = Field(description="Stable check identifier, e.g. 'timeline_1'.")
    question: str = Field(description="Precise verification question for one claim aspect.")
    rationale: str = Field(description="Why this question matters for claim validation.")
    search_queries: list[str] = Field(
        default_factory=list,
        description="Targeted web queries to be used by the investigator.",
    )
    acceptance_criteria: list[str] = Field(
        default_factory=list,
        description=(
            "Concrete 'done when ...' conditions that settle this check, e.g. "
            "'the figure is confirmed by an official statistics release'. Used by the reviewer."
        ),
    )


class InvestigationPlan(BaseModel):
    """Planner output that enumerates checks and explicit assumptions."""
    claim: str = Field(description="Exact claim text being investigated.")
    checks: list[VerificationCheck] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)


class AspectFinding(BaseModel):
    """Research outcome for one planned aspect of the claim."""
    aspect_id: str
    question: str
    signal: EvidenceSignal
    summary: str = Field(description="What the collected evidence says for this aspect.")
    confidence: float = Field(ge=0.0, le=1.0, description="0 to 1 confidence score for this aspect.")
    sources: list[SourceEvidence] = Field(default_factory=list)
    caveats: list[str] = Field(default_factory=list)
    status: SkipJsonSchema[FindingStatus] = FindingStatus.COMPLETED
    failure_reason: SkipJsonSchema[str | None] = None

    @property
    def is_observation(self) -> bool:
        """True when the finding reflects actual research, not a harness failure."""
        return self.status == FindingStatus.COMPLETED


class FactCheckReport(BaseModel):
    """Final verdict artifact combining synthesis, findings, and deduped sources."""
    claim: str
    verdict: VeracityVerdict
    verdict_confidence: float = Field(ge=0.0, le=1.0, description="0 to 1 confidence in final verdict.")
    justification: str = Field(
        description=(
            "Tight synthesis of why the verdict is assigned. Every evidential sentence cites "
            "source ids like [S1]; inferences are marked as such."
        )
    )
    key_points: list[str] = Field(default_factory=list)
    counter_argument: str = Field(
        default="",
        description=(
            "The strongest honest case for a different verdict, grounded in the same findings, "
            "and why it was not adopted."
        ),
    )
    evidence_gaps: list[str] = Field(
        default_factory=list,
        description="Specific evidence that would have changed or firmed up the verdict but was not found.",
    )
    findings: list[AspectFinding] = Field(default_factory=list)
    sources: list[SourceEvidence] = Field(default_factory=list)


class ReviewDecision(BaseModel):
    """Controller decision for bounded review rounds before final judgment."""
    claim: str = Field(description="Exact claim text being reviewed for follow-up research.")
    action: ReviewAction = Field(
        description="Whether to finalize now or request targeted follow-up research."
    )
    rationale: str = Field(description="Why follow-up is or is not needed.")
    gaps: list[str] = Field(
        default_factory=list,
        description=(
            "Concrete evidence gaps found when grading findings against their acceptance criteria; "
            "each follow-up check or retry should trace back to one gap."
        ),
    )
    follow_up_checks: list[VerificationCheck] = Field(
        default_factory=list,
        description="Additional targeted checks to run before the final judgment.",
    )
    retry_aspect_ids: list[str] = Field(
        default_factory=list,
        description="Existing aspect_ids that should be re-run due to weak or failed evidence.",
    )
